# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on Pr's merged by a first time user
firstPRMergeComment: >
  Pull request meged! Congradulations 🚀  You will soon receive an invitation to join MLSC's GitHub organization and showcase it on your profile!
